// Code generated by MockGen. DO NOT EDIT.
// Source: ../../entity/repository_mem.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	entity "shorten/internal/app/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryMem is a mock of RepositoryMem interface.
type MockRepositoryMem struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMemMockRecorder
}

// MockRepositoryMemMockRecorder is the mock recorder for MockRepositoryMem.
type MockRepositoryMemMockRecorder struct {
	mock *MockRepositoryMem
}

// NewMockRepositoryMem creates a new mock instance.
func NewMockRepositoryMem(ctrl *gomock.Controller) *MockRepositoryMem {
	mock := &MockRepositoryMem{ctrl: ctrl}
	mock.recorder = &MockRepositoryMemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryMem) EXPECT() *MockRepositoryMemMockRecorder {
	return m.recorder
}

// GetUrl mocks base method.
func (m *MockRepositoryMem) GetUrl(ctx context.Context, shortenUrl string) (*entity.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrl", ctx, shortenUrl)
	ret0, _ := ret[0].(*entity.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrl indicates an expected call of GetUrl.
func (mr *MockRepositoryMemMockRecorder) GetUrl(ctx, shortenUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrl", reflect.TypeOf((*MockRepositoryMem)(nil).GetUrl), ctx, shortenUrl)
}

// SaveShortenUrl mocks base method.
func (m *MockRepositoryMem) SaveShortenUrl(ctx context.Context, url *entity.Url) (*entity.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortenUrl", ctx, url)
	ret0, _ := ret[0].(*entity.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveShortenUrl indicates an expected call of SaveShortenUrl.
func (mr *MockRepositoryMemMockRecorder) SaveShortenUrl(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortenUrl", reflect.TypeOf((*MockRepositoryMem)(nil).SaveShortenUrl), ctx, url)
}
