# http server config
#
# debug set debug mode, if true, print debug log
# address set http server address
http:
  debug: true
  address: "0.0.0.0:8080"

# log config
#
# debug set debug mode, if true, print debug log
# pretty set pretty mode, aka, human read format, for json format, plz set false
log:
  debug: false
  pretty: false
